stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/train.csv
    - data/test.csv

  model_download:
    cmd: python src/model_download.py
    deps:
    - src/model_download.py
    outs:
    - src/roberta_model
    