stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - params.yaml
    outs:
    - data/train.csv
    - data/test.csv

  # Manual stages 
  model_building:
    cmd: echo "Training performed on Kaggle - see notebooks/model_building_and_eval.ipynb"
    
  model_evaluation:  
    cmd: echo "Evaluation performed on Kaggle - see notebooks/model_building_and_eval.ipynb"
    
  model_registry:
    cmd: echo "Model registration on Weights & Biases via Kaggle - see notebooks/model_building_and_eval.ipynb"